version: "3.9"
services:
  execution:
    image: ethereum/client-go:v1.10.25
    command:
      - --mainnet
      - --http
      - "--http.addr 0.0.0.0"
      - "--http.api net,eth,web3"
      - "--http.vhosts *"
      - "--datadir /var/lib/ethereum/execution"
      - "--authrpc.addr 0.0.0.0"
      - "--authrpc.port 8551"
      - "--authrpc.vhosts *"
      - "--authrpc.jwtsecret /var/lib/ethereum/shared/jwtsecret"
    volumes:
      - /var/lib/ethereum/execution:/var/lib/ethereum/execution:rw
      - /var/lib/ethereum/shared:/var/lib/ethereum/shared:rw
