version: "3.9"
services:
  execution:
    container_name: execution
    image: ethereum/client-go:v1.10.25
    command:
      - --mainnet
      - --http
      - --http.addr
      - "0.0.0.0"
      - --http.api
      - "net,eth,web3"
      - --http.vhosts
      - "*"
      - --datadir
      - "/var/lib/ethereum/execution"
      - --authrpc.addr
      - "0.0.0.0"
      - --authrpc.port
      - "8551"
      - --authrpc.vhosts
      - "*"
      - --authrpc.jwtsecret
      - "/var/lib/ethereum/shared/jwtsecret"
    volumes:
      - /var/lib/ethereum:/var/lib/ethereum:rw
    network_mode: host
    # networks:
    #   - ethereum
  consensus:
    container_name: consensus
    image: sigp/lighthouse:v3.2.1-amd64-modern
    command:
      - lighthouse
      - beacon_node
      - --network
      - mainnet
      - --http
      - --datadir
      - "/var/lib/ethereum/consensus"
      - --execution-endpoint
      - "http://localhost:8551"
      - --execution-jwt
      - "/var/lib/ethereum/shared/jwtsecret"
      - --monitoring-endpoint-period
      - "500"
      - --monitoring-endpoint
      - https://beaconcha.in/api/v1/client/metrics?apikey=${MONITORING_API_KEY}&machine=${MONITORING_MACHINE}
    env_file:
      - .env
    volumes:
      - /var/lib/ethereum:/var/lib/ethereum:rw
    network_mode: host
    # ports:
    #   - 9000:9000
    # networks:
    #   - ethereum
  validator:
    container_name: validator
    image: sigp/lighthouse:v3.2.1-amd64-modern
    command:
      - lighthouse
      - validator_client
      - --graffiti
      - ${VALIDATOR_GRAFFITI}
      - --network
      - mainnet
      - --datadir
      - "/var/lib/ethereum/consensus"
      - --beacon-nodes
      - "http://localhost:5052"
      - --monitoring-endpoint-period
      - "500"
      - --monitoring-endpoint
      - https://beaconcha.in/api/v1/client/metrics?apikey=${MONITORING_API_KEY}&machine=${MONITORING_MACHINE}
    env_file:
      - .env
    volumes:
      - /var/lib/ethereum:/var/lib/ethereum:rw
    network_mode: host
    # networks:
    #   - ethereum
    # networks:
    #   ethereum:
    #     driver: bridge
