version: "3.9"
services:
  execution:
    container_name: execution
    image: ethereum/client-go:v1.15.10
    command:
      - --mainnet
      - --http
      - --http.addr
      - "0.0.0.0"
      - --http.api
      - "net,eth,web3"
      - --http.vhosts
      - "*"
      - --datadir
      - "/var/lib/ethereum/execution"
      - --datadir.ancient
      - "/var/lib/ethereum_ext/geth/ancient"
      - --authrpc.addr
      - "0.0.0.0"
      - --authrpc.port
      - "8551"
      - --authrpc.vhosts
      - "*"
      - --authrpc.jwtsecret
      - "/var/lib/ethereum/shared/jwtsecret"
      - --metrics
      - --metrics.addr
      - "0.0.0.0"
    restart: always
    stop_grace_period: 180s
    volumes:
      - /var/lib/ethereum:/var/lib/ethereum:rw
      - /var/lib/ethereum_ext:/var/lib/ethereum_ext:rw
    network_mode: host
    # networks:
    #   - ethereum
  consensus:
    container_name: consensus
    image: sigp/lighthouse:v7.0.0-amd64
    command:
      - lighthouse
      - beacon_node
      - --network
      - mainnet
      - --http
      - --datadir
      - "/var/lib/ethereum/consensus"
      - --execution-endpoint
      - "http://localhost:8551"
      - --execution-jwt
      - "/var/lib/ethereum/shared/jwtsecret"
      - --monitoring-endpoint-period
      - "500"
      - --monitoring-endpoint
      - https://beaconcha.in/api/v1/client/metrics?apikey=${MONITORING_API_KEY}&machine=${MONITORING_MACHINE}
      - --metrics
      - --builder
      - http://localhost:18550
      - --checkpoint-sync-url
      - https://beaconstate.ethstaker.cc
    env_file:
      - .env
    restart: always
    volumes:
      - /var/lib/ethereum:/var/lib/ethereum:rw
    network_mode: host
  validator:
    container_name: validator
    image: sigp/lighthouse:v7.0.0-amd64
    command:
      - lighthouse
      - validator_client
      - --graffiti
      - ${VALIDATOR_GRAFFITI}
      - --network
      - mainnet
      - --datadir
      - "/var/lib/ethereum/consensus"
      - --beacon-nodes
      - "http://localhost:5052"
      - --monitoring-endpoint-period
      - "500"
      - --monitoring-endpoint
      - https://beaconcha.in/api/v1/client/metrics?apikey=${MONITORING_API_KEY}&machine=${MONITORING_MACHINE}
      - --metrics
      - --builder-proposals
    env_file:
      - .env
    restart: always
    volumes:
      - /var/lib/ethereum:/var/lib/ethereum:rw
    network_mode: host
  mevboost:
    container_name: mevboost
    image: flashbots/mev-boost:1.9
    command:
      - -mainnet
      - -addr
      - 0.0.0.0:18550
      - -relay-check
      - -relay
      - https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net
      - -relay
      - https://0xa1559ace749633b997cb3fdacffb890aeebdb0f5a3b6aaa7eeeaf1a38af0a8fe88b9e4b1f61f236d2e64d95733327a62@relay.ultrasound.money
    env_file:
      - .env
    restart: always
    network_mode: host
