version: "3.9"
services:
  execution:
    image: ethereum/client-go:v1.10.25
    command:
      - --mainnet
      - --http
      - "--http.addr 0.0.0.0"
      - "--http.api net,eth,web3"
      - "--http.vhosts *"
      - "--datadir /var/lib/ethereum/execution"
      - "--authrpc.addr 0.0.0.0"
      - "--authrpc.port 8551"
      - "--authrpc.vhosts *"
      - "--authrpc.jwtsecret /var/lib/ethereum/shared/jwtsecret"
    volumes:
      - type: bind
        source: /var/lib/ethereum/execution
        target: /var/lib/ethereum/execution
      - type: bind
        source: /var/lib/ethereum/execution/shared
        target: /var/lib/ethereum/execution/shared
