version: "3.9"
services:
  execution:
    image: ethereum/client-go:v1.10.25
    command:
      - --mainnet
      - --http
      - --http.addr
      - "0.0.0.0"
      - --http.api
      - "net,eth,web3"
      - --http.vhosts
      - "*"
      - --datadir
      - "/var/lib/ethereum/execution"
      - --authrpc.addr
      - "0.0.0.0"
      - --authrpc.port
      - "8551"
      - --authrpc.vhosts
      - "*"
      - --authrpc.jwtsecret
      - "/var/lib/ethereum/shared/jwtsecret"
    volumes:
      - /var/lib/ethereum:/var/lib/ethereum:rw
    networks:
      - ethereum
  consensus:
    image: sigp/lighthouse:v3.1.2
    command:
      - beacon_node
      - --network
      - mainnet
      - --http
      - --datadir
      - "/var/lib/ethereum/consensus"
      - --execution-endpoint
      - "http://localhost:8551"
      - --execution-jwt
      - "/var/lib/ethereum/shared/jwtsecret"
      # - --monitoring-endpoint ${LIGHTHOUSE_MONITORING_ENDPOINT}
    volumes:
      - /var/lib/ethereum:/var/lib/ethereum:rw
    networks:
      - ethereum
networks:
  ethereum:
    driver: bridge
